# Generated by Django 5.2.17 on 2026-09-03 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ON_TIME', 'On Time'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('COMPLETED', 'Completed')], default='ON_TIME', max_length=20)),
                ('expected_login_time', models.CharField(blank=True, help_text='Expected login time based on gender schedule (10:00 AM Male / 09:30 AM Female)', max_length=20)),
                ('working_hours', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', '-check_in'],
            },
        ),
    ]
