# Generated by Django 5.2.17 on 2026-09-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Per day daily salary rate', max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='days_in_month',
            field=models.IntegerField(default=30, help_text='Total calendar days in target month'),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='leave_days_deducted',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Leave/absence days deducted', max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='leave_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total salary deduction for leave days', max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing')], default='PAID', max_length=20),
        ),
    ]
