# Generated by Django 5.2.17 on 2026-09-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', help_text='Employment Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='Dedicated team member at Thahira Groups.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique Employee ID (e.g., THG-M-01 or THG-F-01)', max_length=20, null=True, unique=True),
        ),
    ]
